spring.application.name=DistributedJobPlatform

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/distributed_job_platform
spring.datasource.username=jobplatform
spring.datasource.password=jobplatform

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer