global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'job-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['job-service:8081']

  - job_name: 'worker-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['worker-service:8082']