apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: distributed-job-platform
type: Opaque
stringData:
  POSTGRES_DB: distributed_job_platform
  POSTGRES_USER: jobplatform
  POSTGRES_PASSWORD: jobplatform